"""`--target local`: docker-compose emulating the sidecar pattern locally.

Bundles the developer's app placeholder, the hardened harness sidecar, and the local
mocks (mock-sandbox = agent-runtime double, mock-mcp = MCP double).
"""
from __future__ import annotations

from typing import Dict

from ._common import dump_yaml, sidecar_env

_RUNTIME_URL = "http://mock-sandbox:8080"
_MCP_URL = "http://mock-mcp:9090"
_GATEWAY_URL = "http://mock-gateway:8081"

_MOCK_BUILD = "../local-dev"

# Same path convention as the webhook's ConfigMap mount (webhook/app.py CONFIG_PATH).
# The shim's Settings.from_env() reads runtime.provider/profile/timeout_seconds and
# source.repo_url/ref EXCLUSIVELY from this mounted file -- none of those have an env
# var fallback, so without this mount the sidecar never learns which repo to clone or
# which sandbox provider to use, regardless of what sidecar_env() sets.
_CONFIG_MOUNT = "/etc/tethricor/harness.yaml"


def generate(config: dict, image: str) -> Dict[str, str]:
    env = sidecar_env(config, runtime_url=_RUNTIME_URL, mcp_url=_MCP_URL, gateway_url=_GATEWAY_URL)
    env["TETHRICOR_CONFIG_PATH"] = _CONFIG_MOUNT

    compose = {
        "services": {
            "app": {
                "image": "busybox:1.36",
                "command": ["sh", "-c", "echo 'replace with your app image'; sleep infinity"],
                "networks": ["tethricor"],
            },
            "harness-sidecar": {
                "image": image,
                "environment": env,
                "volumes": [f"./harness.yaml:{_CONFIG_MOUNT}:ro"],
                "depends_on": ["mock-sandbox", "mock-mcp", "mock-gateway"],
                "networks": ["tethricor"],
                "read_only": True,
                "user": "1001",
                "security_opt": ["no-new-privileges:true"],
                "cap_drop": ["ALL"],
            },
            "mock-sandbox": {
                "build": {"context": _MOCK_BUILD, "dockerfile": "Dockerfile.mock-sandbox"},
                "command": ["python", "mock_sandbox.py"],
                "ports": ["8080:8080"],
                "networks": ["tethricor"],
            },
            "mock-mcp": {
                "build": {"context": _MOCK_BUILD, "dockerfile": "Dockerfile.mock-mcp"},
                "command": ["python", "mock_mcp.py"],
                "ports": ["9090:9090"],
                "networks": ["tethricor"],
            },
            "mock-gateway": {
                "build": {"context": _MOCK_BUILD, "dockerfile": "Dockerfile.mock-gateway"},
                "command": ["python", "mock_gateway.py"],
                "ports": ["8081:8081"],
                "networks": ["tethricor"],
            },
        },
        "networks": {"tethricor": {"driver": "bridge"}},
    }

    readme = (
        "# Local dev bundle\n\n"
        "Generated by `tethricor local-dev --target local`.\n\n"
        "- `harness-sidecar` forwards all execution to `mock-sandbox` (the agent-runtime "
        "double) and routes LLM/MCP via the gateway/mocks.\n"
        "- `harness.yaml` (this bundle's copy of your sanitized config) is mounted "
        f"read-only into `harness-sidecar` at `{_CONFIG_MOUNT}` -- this is how the shim "
        "actually learns runtime.provider, source.repo_url, etc.; the TETHRICOR_* env "
        "vars in docker-compose.yaml are supplementary, not a substitute for it.\n"
        "- Bring your own app image by replacing the `app` service.\n\n"
        "Run: `docker compose up --build`\n"
    )

    return {
        "docker-compose.yaml": dump_yaml(compose),
        "harness.yaml": dump_yaml(config),
        "README.md": readme,
    }
